<?php

/**
 * Implements hook_commerce_order_status_info().
 */
function commerce_abandoned_cart_notification_commerce_order_status_info() {
  $order_statuses = array();

  // Create a new status for orders whom already received a notification.
  $order_statuses['user_notified'] = array(
    'name' => 'user_notified',
    'title' => t('User notified'),
    'state' => 'cart',
    'weight' => 2,
  );

  return $order_statuses;
}


/**
 * Implements hook_views_api().
 */
function commerce_abandoned_cart_notification_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_abandoned_cart_notification') . '/includes/views',
  );
}