<?php

/**
 * @file
 * Defines features and functions common to the
 * Commerce Abandoned Cart Notification module.
 */

/**
 * Implements hook_menu().
 */
function commerce_abandoned_cart_notification_menu() {
  $items['commerce_abandoned_cart_notification/fetch/%commerce_order'] = array(
    'title' => 'Fetch abandoned order',
    'page callback' => 'commerce_abandoned_cart_notification_fetch_order',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_commerce_order_status_info().
 */
function commerce_abandoned_cart_notification_commerce_order_status_info() {
  $order_statuses = array();

  // Create a new status for orders whom already received a notification.
  $order_statuses['user_notified'] = array(
    'name' => 'user_notified',
    'title' => t('User notified'),
    'state' => 'cart',
    'weight' => 2,
  );

  return $order_statuses;
}

/**
 * Implements hook_views_api().
 */
function commerce_abandoned_cart_notification_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_abandoned_cart_notification') . '/includes/views',
  );
}

/**
 * Menu callback; retrieve an abandoned cart.
 */
function commerce_abandoned_cart_notification_fetch_order($order) {
  // If the user is logged in, forward her to the appropriate checkout page.
  if (user_is_logged_in()) {
    drupal_goto(commerce_checkout_order_uri($order));
  }
  else {
    // If the given order is in the user's session, redirect to that order's
    // checkout page.
    if (!empty($_SESSION['commerce_cart_orders']) && in_array($order->order_id, $_SESSION['commerce_cart_orders'])) {
      drupal_goto(commerce_checkout_order_uri($order));
    }
    // Otherwise, display a message indicating that her cookies have expired.
    else {
      drupal_set_message(t('It looks like your browser\'s cookies were cleared or you logged out since starting your order. Please <a href="@url">log in</a> or start a new order to continue.', array('@url' => url('user', array('query' => array('destination' => commerce_checkout_order_uri($order)))))));
      // If possible, forward the user to the product display by which she found
      // the product.
      $line_item = commerce_abandoned_cart_notification_first_product_line_item($order);
      if (!empty($line_item->data['context']['display_path'])) {
        drupal_goto($line_item->data['context']['display_path']);
      }
      // Otherwise, just go to the cart page.
      drupal_goto('cart');
    }
  }
}

/**
 * Retrieve the first line item of an order that references a product.
 */
function commerce_abandoned_cart_notification_first_product_line_item($order) {
  $ids = array_map('_commerce_abandoned_cart_notification_order_line_item_ids', $order->commerce_line_items[LANGUAGE_NONE]);
  $line_items = commerce_line_item_load_multiple($ids);
  foreach ($line_items as $line_item) {
    if ($line_item->type == 'product') {
      return $line_item;
    }
  }
  return FALSE;
}

function _commerce_abandoned_cart_notification_order_line_item_ids($line_item) {
  return $line_item['line_item_id'];
}

/**
 * Implements hook_entity_info().
 */
function commerce_abandoned_cart_notification_entity_info() {
  return array(
    'commerce_abandoned_cart_notification_config' => array(
      'label' => t('Abandoned cart notification config'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'Entity',
      'base table' => 'commerce_abandoned_cart_notification_config',
      'fieldable' => FALSE,
      'label callback' => 'commerce_abandoned_cart_notification_config_label',
      'entity keys' => array(
        'id' => 'id',
      ),
      'admin ui' => array(
        'path' => 'admin/commerce/config/commerce_abandoned_cart_notification',
      ),
    ),
  );
}

/**
 * Implements hook_entity_property_info_alter().
 */
function commerce_abandoned_cart_notification_entity_property_info_alter(&$info) {
  $info['message']['properties']['order'] = array(
    'label' => t('Order'),
    'type' => 'commerce_order',
    'setter callback' => 'entity_property_verbatim_set',
    'computed' => TRUE,
  );
}

/**
 * Implements hook_entity_insert().
 */
function commerce_abandoned_cart_notification_entity_insert($entity, $type) {
  if ($type == 'message' && !empty($entity->order)) {
    $order = commerce_order_load($entity->order);
    $record = array(
      'order_id' => $order->order_id,
      'order_vid' => $order->revision_id,
      'mid' => $entity->mid,
    );
    drupal_write_record('commerce_abandoned_cart_notification', $record);
  }
}

/**
 * Implements hook_entity_load().
 */
function commerce_abandoned_cart_notification_entity_load($entities, $type) {
  if ($type == 'message') {
    // Get all the order IDs at once to minimize database queries.
    $mids = array_map('_commerce_abandoned_cart_notification_mids', $entities);
    $result = db_select('commerce_abandoned_cart_notification', 'cacn')
      ->fields('cacn')
      ->condition('mid', $mids)
      ->execute()
      ->fetchAll();

    // Match the orders to their message entities.
    foreach ($result as $row) {
      foreach ($entities as $entity) {
        if ($row->mid == $entity->mid) {
          $entity->order = commerce_order_load($row->order_id);
          // Skip to the next $row.
          break;
        }
      }
    }
  }
}

function _commerce_abandoned_cart_notification_mids($item) {
  return $item->mid;
}

function _commerce_abandoned_cart_notification_order_ids($item) {
  return $item->order_id;
}
